# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: windows-agent-sonal

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'endpoint-for-sonarqube-new'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'sonal'
    cliSources: '.'

- task: SonarQubeAnalyze@8
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'