# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: windows-agent-sonal

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SonarCloudPrepare@4
  inputs:
    SonarQube: 'sonarcloude-kawalesonal'
    organization: 'kawalesonal5'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'abcd'
    cliSources: '.'

- task: SonarCloudAnalyze@4
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@4
  inputs:
    pollingTimeoutSec: '300'